### PR TITLE
format files and add router and store

### PR DESCRIPTION
**Pull request by abcotter**
@CarlaLeal I altered the frontend set up to allow us to harness vue-router and store :) lets have a chat of if we want to add this packges to the docker image so the team doesn't have to run npm install on them

### CODE REVIEW

**Review by CarlaLeal — COMMENTED** [review]
What do you think about keeping the node modules off Github so that we can work with a more lightweight repository that is a bit easier to follow. Could we add vuex and vue-router to the package.json and ask our team members to run npm instal --save-dav?

**Comment by abcotter** [comment]
@CarlaLeal, yea I agree! let's keep node_modules out :) I move them into the frontend/frontend folder to get picked up by the git ignore, also they appear to show up int the vue GUI, so the team can install them vie the read.me steps!

**Comment by CarlaLeal** [comment]
> @CarlaLeal, yea I agree! let's keep node_modules out :) I move them into the frontend/frontend folder to get picked up by the git ignore, also they appear to show up int the vue GUI, so the team can install them vie the read.me steps!

Okay and just to make sure you mean this read me right: https://github.com/FatimahAreola/MSCI-342-Group-Project/blob/main/frontend/frontend/README.md.

**Comment by abcotter** [comment]
@CarlaLeal no I mean the repo read.me https://github.com/FatimahAreola/MSCI-342-Group-Project/blob/main/README.md, i added an extra step

**Pull request merged**
